### ISSUE TITLE
issue on ios10 using the plugin on a native modal view

### ISSUE THREAD

**Issue by rafaeluzzi** [EddyVerbruggen/cordova-plugin-actionsheet#45] opened 2016-09-19 16:10 UTC
First thanks for the awesome plugin.

Im having a problem when I use this plugin on a native modal view(im using appgyver steroids), actionsheet loads fine but when any button is pressed it just close the modal view. It works fine on webviews this issue is just happening on modal views and it was working fine on the previous version. 

Any ideas?

**Comment by EddyVerbruggen** [comment] 2016-09-19 16:29
No idea really. I swapped implementations to a more modern framework (since version 2.3.1) but dismissing the actionsheet is done in a similar manner.

Is this reproducible without Appgyver?

**Comment by rafaeluzzi** [comment] 2016-09-19 17:58
can't reproduce without appgyver as steroids is the one providing the native modal view, seems like the dismisal method is also dismissing the parent view when this view is a modal view.

**Comment by cdelafuente** [comment] 2016-09-22 23:56
I ran into the same error when using an action sheet in a modal with Appgyver. I got around the issue by displaying the view using `supersonic.ui.layers.push()`.

**Comment by chemerisuk** [comment] 2016-09-30 22:38
Not sure if it's related or not... On iOS10 when user dismisses an actionsheet via tapping on a dark screen background (on iPad at least), the plugin stops working. Next show() calls do not work anymore.

**Comment by gitlovenotwar** [comment] 2016-11-17 05:48
@chemerisuk I'm having the same problem. It crashes the app tapping outside. Also, callback buttons not even firing, after next show, it doesn't work anymore.

**Comment by EddyVerbruggen** [comment] 2016-11-21 12:46
Tried again with a host of sims and devices (iPad and iPhone) and everything was fine with my vanilla Cordova CLI testapp.

Closing this, but if one of you is able to come up with a very simple vanilla testcase then please reopen and link to the download.

**Closed by EddyVerbruggen** 2016-11-21 12:46 UTC
